### ISSUE TITLE
Organize first NodeSchool Event at HH

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#2]
This is the main Orga thread.
- [x] schedule the event (_see #8_)
- [x] contact some possible sponsors (_see #6_)
- [x] find the location
- [x] advertise the event
- [x] find some Mentors (_see #7_)

**Comment by mdunisch** [comment]
Hello :-)

**Comment by finnp** [comment]
Depending on when we do this, I would consider coming to Hamburg for this.

**Comment by greelgorke** [comment]
Cool! I think about early november, may be earlier.

Hi @mdunisch, wanna join :)?

**Comment by mdunisch** [comment]
sure ;-)

**Comment by greelgorke** [comment]
When i'm in the office

**Comment by greelgorke** [comment]
Let talk about the **when**
- Workday or Saturday or Sunday?
- October, November, December?

currently i'd prefer the first Week of November.

**Comment by robertkowalski** [comment]
+1 on a Saturday as there is more time and on Sunday folks don't want to leave the house

**Comment by mdunisch** [comment]
+1 Saturday

**Comment by greelgorke** [comment]
Doodle Link in #8 !

**Comment by greelgorke** [comment]
I'll advertise it on Monday at the HH.js

**Comment by afknapping** [comment]
ah, didn't catch this – since berlin was an evening event, i thought this will be too :)

then having something for lunch makes sense of course, sorry.

**Comment by greelgorke** [comment]
i need someone to write some text for the event announcement on nodescool.io and tito. anybody? i didn't found time, i think wont till thursday of the next week. volunteers?

**Comment by finnp** [comment]
@greelgorke I just edited the Berlin Feedback form for Hamburg. It's quite short, but if you like it you can just use it. It's only in English though.

**Comment by greelgorke** [comment]
i need a link @finnp  :)
